### PR TITLE
Add examples for `twitch` lib

### PR DESCRIPTION
**Pull request by trezy**

### CODE REVIEW

**Comment by trezy** [comment]
Hey @d-fischer, could you verify that these examples look right for `twitch.js`?

| Example | URL |
| - | - |
| Connecting | https://fdgt-website-h27yxpu5t.vercel.app/docs/getting-started |
| Sending messages | https://fdgt-website-h27yxpu5t.vercel.app/docs/api/bits |

**Comment by trezy** [comment]
Mentioning @denchp here, too, since I know you had some interest in this.

**Comment by trezy** [comment]
From @d-fischer on Discord:
> `withClientCredentials` setups don't work with chat, never have
> Before 4.1 it would try to get a scope and fail, starting with 4.1 it would see that an app token is being generated and fail early

So, should the example use `Twitch.withCredentials()` instead? Or is there a way to join with the anonymous `justinfan` data to simplify the example? The goal is to have an example that’s as small as possible, but that will work if dropped directly into an app.

**Comment by d-fischer** [comment]
You could actually put a static token into `withCredentials`, but that would set a terrible example since a refreshable token should be the norm. 

An anonymous/justinfan connection can be made with `ChatClient.anonymous({ hostName });`.

**Comment by trezy** [comment]
@all-contributors add @d-fischer for docs and review

**Pull request merged**
